# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbtCloudCli < Formula
  desc "dbt Labs' CLI."
  homepage "https://github.com/dbt-labs/homebrew-dbt-cli"
  version "0.28.2"

  on_macos do
    url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.28.2/dbt_0.28.2_darwin_all.tar.gz"
    sha256 "e77a487827f925d7e16665fed920c6b5de388a221f17ea6301bda3d3a5444255"

    def install
      bin.install "dbt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.28.2/dbt_0.28.2_linux_armv6.tar.gz"
      sha256 "99797fa8cdc5c15c2c696e2ad26f144c4839e95550ce2a2b6a892d9b57df68b3"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.28.2/dbt_0.28.2_linux_amd64.tar.gz"
      sha256 "3773b94b81d283fcac5f88fd2bc5f280ceb8e7b1b52f551b98e308a55ae6d52a"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.28.2/dbt_0.28.2_linux_arm64.tar.gz"
      sha256 "60ef6a8c19fffccc7a5b3dff0e93ddfd1341b60e5b1dea3f7d019340060fb8ab"

      def install
        bin.install "dbt"
      end
    end
  end
end
