# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbt < Formula
  desc "dbt Labs' CLI."
  homepage "https://github.com/dbt-labs/homebrew-dbt-cli"
  version "0.38.0"

  on_macos do
    url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.0/dbt_0.38.0_darwin_all.tar.gz"
    sha256 "b002827c0abfa853ce7ae4c18f913d353cffb8832d7a3ab6ea49d95cdb6f3b96"

    def install
      bin.install "dbt"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.0/dbt_0.38.0_linux_amd64.tar.gz"
        sha256 "2870b69d7a174313b42423a9158288dc5cc8ac8b01705089d7e40ce8926e091d"

        def install
          bin.install "dbt"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.0/dbt_0.38.0_linux_armv6.tar.gz"
        sha256 "147987f95fbfb54cd408845a62775eff9f1b8736fb4d9692c2407103bf618dd0"

        def install
          bin.install "dbt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.38.0/dbt_0.38.0_linux_arm64.tar.gz"
        sha256 "936ef1ba16a355db440688d98a580f161b823c3be594625af5a4f11c6c023784"

        def install
          bin.install "dbt"
        end
      end
    end
  end
end
