# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbt < Formula
  desc "dbt Labs' CLI."
  homepage "https://github.com/dbt-labs/homebrew-dbt-cli"
  version "0.35.23"

  on_macos do
    url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.35.23/dbt_0.35.23_darwin_all.tar.gz"
    sha256 "729fffe327d96054337453fe96cb16e5fd6c56911b33f7d55e185144c9dd9305"

    def install
      bin.install "dbt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.35.23/dbt_0.35.23_linux_arm64.tar.gz"
      sha256 "3592e5466809f786087c28775d001ed8273a3ffaebc1fff7667a83ecd6da93c0"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.35.23/dbt_0.35.23_linux_amd64.tar.gz"
      sha256 "659c077d5ecd9958a2438979c7e2c1f2d0abe00d3240fc34bf9de33a7aa8c360"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.35.23/dbt_0.35.23_linux_armv6.tar.gz"
      sha256 "7076112f9020b34733640189334212d74fcd32c805b1a914a96dff7c706d7b5d"

      def install
        bin.install "dbt"
      end
    end
  end
end
