# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbt < Formula
  desc "dbt Labs' CLI."
  homepage "https://github.com/dbt-labs/homebrew-dbt-cli"
  version "0.34.8"

  on_macos do
    url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.34.8/dbt_0.34.8_darwin_all.tar.gz"
    sha256 "57291d8fb35d8330a9c10ce4b5369e76bb21eb652bb5bdb839b928dac338c1b4"

    def install
      bin.install "dbt"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.34.8/dbt_0.34.8_linux_arm64.tar.gz"
      sha256 "7de7901318a4f2a827b892bf4f1af8914cf0ba1a90102550b18ed107f9231431"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.34.8/dbt_0.34.8_linux_amd64.tar.gz"
      sha256 "e19ea01d50ba16dfef9ef1c5c3a609fd5d84c4b9dd75b1e9beb93a1720c93573"

      def install
        bin.install "dbt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbt-cli/releases/download/v0.34.8/dbt_0.34.8_linux_armv6.tar.gz"
      sha256 "90c7dbc03d0bd83104942d23262b2ed741043fe32b017de0735a8d49cf64de86"

      def install
        bin.install "dbt"
      end
    end
  end
end
