# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbtcloudTerraforming < Formula
  desc "CLI tool to help importing existing dbt Cloud configuration to Terraform"
  homepage "https://github.com/dbt-labs/dbtcloud-terraforming"
  version "0.3.3"

  on_macos do
    url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.3.3/dbtcloud-terraforming_0.3.3_darwin_all.tar.gz"
    sha256 "3b472eabdfafa106313843f7e6c72c25ca003fab508bdc8680836552e09faab6"

    def install
      bin.install "dbtcloud-terraforming"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.3.3/dbtcloud-terraforming_0.3.3_linux_arm64.tar.gz"
      sha256 "104f84cae4f285a1eeb16e9f5a79e423de540935490661f7e081818a4292c915"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.3.3/dbtcloud-terraforming_0.3.3_linux_amd64.tar.gz"
      sha256 "97cca9017885460ed1eba896fc8cf8bafb6d0279f0eac62e24bee663d19833bb"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.3.3/dbtcloud-terraforming_0.3.3_linux_armv6.tar.gz"
      sha256 "34df36cf8f82ad7c1fed93a37d796bdc92cdeba5532cbb4d28db4fa184a38e6c"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
  end
end
