# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbtcloudTerraforming < Formula
  desc "CLI tool to help importing existing dbt Cloud configuration to Terraform"
  homepage "https://github.com/dbt-labs/dbtcloud-terraforming"
  version "0.5.0"

  on_macos do
    url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.5.0/dbtcloud-terraforming_0.5.0_darwin_all.tar.gz"
    sha256 "526bfbbc0b57eaf36c7c670a5d8451ba9e8342bf766801eaa5f0c14beb4cd017"

    def install
      bin.install "dbtcloud-terraforming"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.5.0/dbtcloud-terraforming_0.5.0_linux_amd64.tar.gz"
      sha256 "0f8e4c36489d5ed92abd59d6a3b19273bbcb79680e2e9f97153da72d34128313"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.5.0/dbtcloud-terraforming_0.5.0_linux_armv6.tar.gz"
      sha256 "84ba00535fa7332cbb0dc8f15c49e2c9a83e28858f5d6ffa0de8bf87387977ce"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.5.0/dbtcloud-terraforming_0.5.0_linux_arm64.tar.gz"
      sha256 "038bb23e6e30a2ef7256c4f9c84fe06b840833c52da586b02e08b12c16ed1d0f"

      def install
        bin.install "dbtcloud-terraforming"
      end
    end
  end
end
