# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DbtcloudTerraforming < Formula
  desc "CLI tool to help importing existing dbt Cloud configuration to Terraform"
  homepage "https://github.com/dbt-labs/dbtcloud-terraforming"
  version "0.12.3"

  on_macos do
    url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.12.3/dbtcloud-terraforming_0.12.3_darwin_all.tar.gz"
    sha256 "ccb7d88359db804e06222af81e57334630abed2b431fd1a6e56499efae7b4c6a"

    def install
      bin.install "dbtcloud-terraforming"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.12.3/dbtcloud-terraforming_0.12.3_linux_amd64.tar.gz"
        sha256 "aeb5d9bb5d9ff9d56277de84477458014a3590939a145296fba9fab56fe8ae80"

        def install
          bin.install "dbtcloud-terraforming"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.12.3/dbtcloud-terraforming_0.12.3_linux_armv6.tar.gz"
        sha256 "081df456397122e642a53d00854fac809cd7b014eb059baafd42af0a31ebe968"

        def install
          bin.install "dbtcloud-terraforming"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dbt-labs/dbtcloud-terraforming/releases/download/v0.12.3/dbtcloud-terraforming_0.12.3_linux_arm64.tar.gz"
        sha256 "247e545bdebfa35e50f5442311524c9668c271ba3ea5c6efd2eb4e964cce6a68"

        def install
          bin.install "dbtcloud-terraforming"
        end
      end
    end
  end
end
